### ISSUE TITLE
关于TIS中禁用SmartScreen的非严谨判断

### ISSUE THREAD

**Issue by ZXGU183** [whatk233/tis#11]
[DisableSmartScreen](https://github.com/whatk233/tis/blob/main/tweaks/Security/DisableSmartScreen.yaml)
>    - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'
      valueName: "SmartScreenEnabled"
      action: delete

已知直接删除注册表中的该值会造成DISM++中对应功能 **关闭SmartScreen应用筛选器** 为关闭状态，初步判断SmartScreen进程会运行而不是被禁用
*没有经过严格的检查，不保证判断可靠*

**Comment by whatk233** [comment]
Fixed, thank you

ref: https://admx.help/?Category=Windows_8.1_2012R2&Policy=Microsoft.Policies.WindowsExplorer::EnableSmartScreen
